spring:
  application:
    name: job-server
  jpa:
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 16384